name: Publish to GitHub Packages

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download & unzip protoc
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-linux-x86_64.zip \
            -O protoc-3.zip
          unzip protoc-3.zip -d protoc-3
          mv protoc-3/bin/protoc protoc

      - name: Compile java files from `proto` file
        run: |
          ./protoc --java_out=./src/main/java/ src/main/protos/de/cyface/protos/model/measurement.proto

      # Publish slim JARS to Github Package Registry
      - name: Publish package
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      # Automatically mark this tag as release on Github
      - uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          # Release tags of format `1.2.3-beta1 / -alpha1 / -test1` are considered a pre-release
          prerelease: ${{ contains(github.ref, 'test') || contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
